### ISSUE TITLE
No issue just question

### ISSUE THREAD

**Issue by sherpascott** [Tape-Dispenser/Immersive-Music-Mod#11]
I didn’t know how else to reach you sorry! I was just wondering if I could use some of your music in a custom resource pack for a modpack I’ve made? Crediting you of course.

**Comment by Tape-Dispenser** [comment]
I am not the composer of any of the music, however you can contact the composer on discord, his tag is `goldeagleproductions`. To my knowledge so long as you don't profit off the music or claim it's yours you should be good to use it and remix it though. @GoldEagleProductions

**Comment by GoldEagleProductions** [comment]
Yeah go ahead with the music. We have a discord (discord.gg/zPZP9RT253) and my youtube channel (Gold Eagle Productions) so either place is good to contact us... or here as well I suppose lol. Thanks for asking, yes go ahead and use the music, I would be interested in how it turns out as well
