### ISSUE TITLE
Bug: Skip command doesn't fully work(?)

### ISSUE THREAD

**Issue by alexzander700** [Tape-Dispenser/Immersive-Music-Mod#21]
![image](https://github.com/Tape-Dispenser/Immersive-Music-Mod/assets/51793351/cd90383c-34b3-4e54-aa64-02307568f8d2)
Every time I do the skip command, the music stops playing and it says the above error.

I'm using Quilt 1.20.1 (v0.24.0) (Going to try updating this to v0.25.0 to see if it fixes)
Mod version: "timm-1.0.2 for 1.20.1.jar"

**Comment by alexzander700** [comment]
![image](https://github.com/Tape-Dispenser/Immersive-Music-Mod/assets/51793351/ebd761d5-c29a-42c2-96b1-7adf16d88410)
Would any of these be a reason for the issues?

**Comment by alexzander700** [comment]
Custom music *does* work with Quilt, it's just an error in chat as far as I can see

**Comment by Tape-Dispenser** [comment]
yeah `/skip` has that bug in a couple of versions, it prints an error to chat but it should still run the command properly. this bug has been patched already (see issue #16) and will be fixed in all minecraft versions in TIMM 1.0.3
