### ISSUE TITLE
Question - Compatibility with resource packs that add music?

### ISSUE THREAD

**Issue by floral-qua-floral** [Tape-Dispenser/Immersive-Music-Mod#22]
Hello! I'm really interested in this mod, and I was wondering whether it will work well alongside resource packs that add additional ambient music tracks. Specifically, I'm considering using it with [Music and Melody](https://modrinth.com/resourcepack/music-and-melody), however I'm not sure whether or not they'll work together. Will the music from this mod and that resource pack both play, or will Immersive Music Mod prevent Music and Melody's tracks from playing?

**Comment by Tape-Dispenser** [comment]
Compatibility with other mods is something that's being worked on, however without testing I can't say for certain if this mod is compatible with Music and Melody. Feel free to give it a try and open another bug report if it doesn't work though!
