### ISSUE TITLE
Replace mod 'Fabric Loader' (fabricloader) 0.14.14 with version 0.14.21 or later.

### ISSUE THREAD

**Issue by tuanguyenbr** [Tape-Dispenser/Immersive-Music-Mod#24]
"Mod 'The Immersive Music Mod' (timm) 1.0.2 requires version 0.14.21 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.14!"
it said that my Fabric Loader is at wrong version but i have no mod with that name, even the version. my Fabric-api is 0.77

**Comment by Tape-Dispenser** [comment]
you need to reinstall fabric using fabric version 0.14.21 or higher
