### ISSUE TITLE
The mod plays only vanilla songs in multiplayer

### ISSUE THREAD

**Issue by DimetryBadcoder** [Tape-Dispenser/Immersive-Music-Mod#25]
We are using dedicated server

**Comment by DimetryBadcoder** [comment]
I just noticed, that if you use /skip command, the mod chooses new ones, and everything looks fixed

**Comment by DimetryBadcoder** [comment]
I just realised that there is no new music for river and savanna. 
In nether and dripstone caves everything is fine. 
It might be not multiplayer problem

**Comment by Tape-Dispenser** [comment]
yeah i believe the river, savanna, and beach biomes don't have any songs for them in the current version of the mod. this will be fixed in the next update.

**Comment by DimetryBadcoder** [comment]
Good!
