### ISSUE TITLE
Ability to add/replace music?

### ISSUE THREAD

**Issue by Zortabre** [Tape-Dispenser/Immersive-Music-Mod#27]
Hello, I was wondering if it's possible to add or replace music files and configure new music tracks to work for specific biomes.

**Comment by Tape-Dispenser** [comment]
in the current release version of the mod, you can configure which songs play in which biomes, this data is stored in your `.minecraft/config/timm/biome_playlists.json` file, all songs you add must be a registered song in minecraft or another mod (for example, `minecraft:music.game`, `timm:taiga`, or `alexscaves:magnetic_caves_music`.) In the upcoming version of the mod, you will also be able to load any .ogg audio file on your computer into the game, as well as enable/disable any songs you wish.

**Comment by Tape-Dispenser** [comment]
as for replacing songs in the current version you can use a resource pack to replace songs in either minecraft or timm

**Comment by Zortabre** [comment]
thanks for the quick response! do you know if there's any documentation about music replacement resource packs that work with this mod?

**Comment by Tape-Dispenser** [comment]
sorry about the delayed response, i don't know of any specific resource packs that do this but any pack that changes out either vanilla sounds (currently the only vanilla sound the mod uses is `minecraft:music.game` or any of the timm sounds (a list of timm sounds can be found at https://github.com/Tape-Dispenser/Immersive-Music-Mod/tree/main/src/client/resources/assets/timm/sounds.json and https://github.com/Tape-Dispenser/Immersive-Music-Mod/tree/main/src/client/resources/assets/sounds) should work for your use case.
