### ISSUE TITLE
The music changes when you click done in the options

### ISSUE THREAD

**Issue by MixterioH** [Tape-Dispenser/Immersive-Music-Mod#8]
The music changes every time you click any button to return to the main menu, example:
Go to (Options) then (Done) or (Multiplayer) then (Cancel).

**Comment by Tape-Dispenser** [comment]
currently investigating the issue

**Comment by Tape-Dispenser** [comment]
@MixterioH what version of the mod are you using? I could not replicate the issue on the latest version of the mod

**Comment by MixterioH** [comment]
Desculpe pela demora, não costumo ir muito ao github, mas estou usando a versão minecraft-0.1_b4, acabei de testar sem nenhum mod diferente do Fabric API 0.91.0+1.20.1 e o problema persiste, a versão que estou usando do carregador de tecido é 0.14.25. Eu testei em 2 launchers, ATlauncher e vanilla.

**Comment by MixterioH** [comment]
Sorry for the delay, I don't usually go to github much, but I'm using the minecraft-0.1_b4 version, I just tested it without any mod other than Fabric API 0.91.0+1.20.1 and the problem persists, the version I'm using of the loader of fabric is 0.14.25. I tested it on 2 launchers, ATlauncher and vanilla.

**Comment by MixterioH** [comment]
Here is a video of the problem occurring:

https://github.com/Tape-Dispenser/Immersive-Music-Mod/assets/37636267/5371366d-d099-40cf-aba8-0abfb4a305bd

**Comment by Tape-Dispenser** [comment]
thank you for the video, however i cannot hear any audio from it. I will investigate further, although i'm fairly certain this issue is already fixed in the upcoming beta version

**Comment by Tape-Dispenser** [comment]
bug still exists in latest version of source code
